name: dp gpt

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image, Push
        run: |
          cd pj1
          timestamp=$(date -u +'%Y%m%d-%H%M%S')
          echo "Using timestamp: $timestamp"
          docker build -t zzdnb/docker_django_demo:$timestamp .
          docker tag zzdnb/docker_django_demo:$timestamp zzdnb/docker_django_demo:latest
          docker push zzdnb/docker_django_demo:$timestamp
          docker push zzdnb/docker_django_demo:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      
      - name: Deploy to Tencent Cloud
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TENCENT_HOST }}
          username: ${{ secrets.TENCENT_USERNAME }}
          key: ${{ secrets.TENCENT_PRI_SSH_KEY }}
          # password: ${{ secrets.TENCENT_PASSWORD }}
          script: |
            cd /www/wwwroot/docker-django-demo
            git pull
            echo "PJ1_IMAGE=${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}" >> .env
            sudo docker compose up --build -d